console.log('1: start');
const path = require('path');
console.log('2: path loaded');
require('dotenv').config();
console.log('3: dotenv configured');
const express = require('express');
console.log('4: express loaded');
const http = require('http');
console.log('5: http loaded');
const { Server } = require('socket.io');
console.log('6: socket.io loaded');
const app = express();
console.log('7: app created');
app.use(express.static(path.join(__dirname, '..', 'public')));
console.log('8: static mounted');
const server = http.createServer(app);
console.log('9: server created');
const io = new Server(server);
console.log('10: io created');
const PORT = process.env.PORT;
console.log('11: PORT =', PORT);
server.listen(PORT, () => console.log('12: LISTENING on', PORT));
console.log('13: listen() called, waiting...');
